### ISSUE TITLE
Cyclops Error with Julia 1.1

### ISSUE THREAD

**Issue by zzj0402** [SciML/NeuralPDE.jl#146]
```
(v1.1) pkg> add NeuralPDE
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package NeuralPDE [315f7962]:
 NeuralPDE [315f7962] log:
 ├─possible versions are: [2.0.0, 2.1.0, 2.2.0, 2.3.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [2.0.0, 2.1.0, 2.2.0, 2.3.0]
 ├─restricted by compatibility requirements with CuArrays [3a865a2d] to versions: [2.1.0, 2.2.0, 2.3.0] or uninstalled, leaving only versions: [2.1.0, 2.2.0, 2.3.0]
 │ └─CuArrays [3a865a2d] log:
 │   ├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled
 │   └─restricted to versions 1.2.1 by an explicit requirement, leaving only versions 1.2.1
 └─restricted by compatibility requirements with Flux [587475ba] to versions: uninstalled — no versions left
   └─Flux [587475ba] log:
     ├─possible versions are: [0.4.1, 0.5.0-0.5.4, 0.6.0-0.6.10, 0.7.0-0.7.3, 0.8.0-0.8.3, 0.9.0, 0.10.0-0.10.4, 0.11.0-0.11.1] or uninstalled
     └─restricted to versions 0.9.0 by an explicit requirement, leaving only versions 0.9.0
```

**Comment by ChrisRackauckas** [comment]
CuArrays.jl is the old old way and you should remove it and use CUDA.jl instead.

**Comment by zzj0402** [comment]
How to modify that? What's the proper way to modify dependency in a package?

**Comment by ChrisRackauckas** [comment]
Oh, I see the issue.. NeuralPDE.jl requires Julia v1.3 for any of its recent versions. 

https://github.com/SciML/NeuralPDE.jl/blob/master/Project.toml#L44

The solution here is to just not use Julia v1.1 for this package. We don't plan to support v1.1 since it doesn't have all of the parallel primitives that we use, and it hasn't been available as a standard download for a few years. Any codes written for v1.1 will work on later v1.x Julia's so upgrading is straightforward for the user and that's what I'll have to recommend.

Is there a reason you chose v1.1 on Cyclops? I assume that must be what was pre-installed? Most people using Cyclops are probably grabbing the generic binary or building from source instead (the group using Cyclops is a fairly different crew from the standard user).

**Comment by ChrisRackauckas** [comment]
I'll close this since we don't plan to support v1.1, but feel free to continue discussion of course.
