### ISSUE TITLE
Collocation points, Initial points, Boundary points, and the activation function

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [SciML/NeuralPDE.jl#197]
If we use "NeuralPDE.jl", how can I know the following important information from the PINNS model

**Collocation points, Initial points, Boundary points, and the Activation function**

1. **Collocation points**

2. **Initial points**

3. **Boundary points**

4. **Activation function**

coordinate of these points, etc.

**Comment by ChrisRackauckas** [comment]
There are no "points": it's a continuous model. There are points the loss is evaluated at but in some strategies that changes every time. The boundary is continuous, the initial condition is just a boundary condition. You pass in the neural network so you know the activation function you specify in the `Chain` objects. There's no such thing as a collocation point in this method, or at least, it's not well-defined just like the other points.

Hopefully that answers everything? I'm going to close this because there's nothing else to do, but feel free to continue discussing. This is a really odd question though.
