### ISSUE TITLE
Error in the parser for multiplication between differentials

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#234]
the expression isn't handled :
```julia
expr = (Dx(k(x)) * Dx(T(t, x)))
```

**Comment by bgroenks96** [comment]
There's a misplaced parentheses in the expression. It should be: `Dx(k(x)*Dx(T(t,x)))`

i.e. a nonlinear diffusion function.

**Comment by killah-t-cell** [comment]
I think this is working as expected. Just tested it with `Dx(u(x, t) * Dx(w(x, t))) ~ 0`. It seems to work as expected.

Running transform_expression returns `0 ~ Differential(x)(Differential(x)(w(x, t))*u(x, t))`
Running build_loss_function returns `:((Differential(x))((Differential(x))((u⋆)(cord, var"##θ#368", phi))) * (u⋆)(cord, var"##θ#368", phi) + (Differential(x))((u⋆)(cord, var"##θ#368", phi)) * (Differential(x))((u⋆)(cord, var"##θ#368", phi)))`

It seems to apply the product rule correctly.

If I were to guess, @KirillZubov's example didn't work because of either the misplaced parentheses or the fact that we don't yet support heterogenous inputs.

**Comment by KirillZubov** [comment]
we need tests for the parser

**Comment by killah-t-cell** [comment]
What tests do you imagine?

**Comment by KirillZubov** [comment]
@killah-t-cell  I think something like that
```julia
@parameters x
@variables u(..)

Dx = Differential(x)
eq = Dx(u(x)) ~ 0.
bcs = [u(0.) ~ u(0.)]
domains = [x ∈ Interval(0.0,1.0)]
chain = FastChain((x,p) -> x.^2)

chain([1],Float32[])
strategy_ = NeuralPDE.GridTraining(0.1)
discretization = NeuralPDE.PhysicsInformedNN(chain,strategy_)
pde_system = PDESystem(eq,bcs,domains,[x],[u])
prob = NeuralPDE.discretize(pde_system,discretization)

train_data =prob.f.f.loss_function.pde_loss_function.pde_loss_functions.contents[1].train_set
inner_loss =prob.f.f.loss_function.pde_loss_function.pde_loss_functions.contents[1].loss_function

dudx(x) = @. 2*x
@test inner_loss(train_data, Float32[]) ≈ dudx(train_data) rtol = 0.001
```
