### ISSUE TITLE
kwarg isFloat32 

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#323]
I think it needs to add a flag that determines the accuracy of the calc.
isFloat32 = True/False, default True
```julia
discretization = NeuralPDE.PhysicsInformedNN(chain,
                                                 strategy_;
                                                 init_params = nothing,
                                                 phi = nothing,
                                                 derivative = nothing,
                                                 isFloat32 = true
                                                 )
```
it needs to add conversion of constants to the desired type in the parser

**Comment by ChrisRackauckas** [comment]
No, it should not be done like that. It should just follow the input types. There's no reason to avoid `eltype(p)` stuff because the compiler always hoists those out to no-ops. There's literally zero runtime cost to doing so. There's no reason to specialize on `Float32`: it can just follow the input element types.

**Comment by ChrisRackauckas** [comment]
We can chat about these some more, but these last two issues are very worrisome. That's exactly the opposite of generic programming.

**Comment by KirillZubov** [comment]
ok, I got it
