### ISSUE TITLE
kwarg isGPU

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#324]
In order to calculating with GPU requires an understandable parameter, 
instead `initθ = DiffEqFlux.initial_params(chain) |> gpu`.
I think better
```julia
discretization = NeuralPDE.PhysicsInformedNN(chain,
                                             strategy;
                                             init_params = initθ,
                                             isGPU=true)
```

**Comment by ChrisRackauckas** [comment]
No, because that's a lot less general. What about TPU support? AMDGPU support? Multi-GPU support? All of those already have a one line solution. There's no reason to put this into the package: it would decrease the features, increase the amount that has to be maintained, and increase the amount that has to be documented.

**Comment by KirillZubov** [comment]
ok, I got it
