### ISSUE TITLE
Specify loss function directly for NeuralPDE?

### ISSUE THREAD

**Issue by raminammour** [SciML/NeuralPDE.jl#496]
(Originally posted on [discourse](https://discourse.julialang.org/t/specify-loss-function-directly-for-neuralpde/77757))

In NeuralPDE you normally define the PDE ( `rhs = lhs`) symbolically and the loss function is built internally, loosely  `\int dvars ||lhs(vars) - rhs(vars)||^2`.

Is there a way to specify the objective function symbolically directly? Let’s say you are crazy enough and just want to optimize 
`\int dvars cos(lhs(vars) + sin(rhs(vars))` . What would be the easiest way to do that?

@ChrisRackauckas directed me to open an issue to maybe add some support/API to that without having to hack too much code.

Cheers!

**Comment by zoemcc** [comment]
The current best way to do that would be to add your special loss function through the additional_loss function functionality and then pass in a dummy pde equation such as `x~x`  for your pde equation so that it doesn't optimize the original loss function.  Or you could leave the original loss function if you want to optimize a sum of your special loss and the generated loss.  

Once we make a release for the adaptive loss PR that just merged ( https://github.com/SciML/NeuralPDE.jl/pull/482 ), you can leave the original pde as-is and then pass in a 0 weight for that particular pde equation using the `NonAdaptiveLoss` struct https://github.com/SciML/NeuralPDE.jl/blob/d983a0a50bafc0a92f8be84d900111b33a44344e/src/pinns_pde_solve.jl#L255 .  This would be slightly less computationally efficient than the current workaround I suggested since you would compute the generated loss each iteration but is conceptually simpler than the workaround.

**Comment by raminammour** [comment]
Thank you for your reply, I will have to dig in deeper to figure out the details but I had figured out that I would need to implement the numerical integral approximation on my side with `additional_loss`.

My thinking was, since you support integro-differential equations, it should be possible to define the loss function symbolically with using integrals over the domain, and the rest would follow from the internals since you are having to do that work anyway to construct the loss function. I am confident it is possible, not sure how hard it would be to support that API though :)

I had also thought about the appropriate transformations and had come up with similar forms, but I will have to dig deeper to make it technically work (positivity and other constraints, as you said...).

**Comment by ChrisRackauckas** [comment]
An example of this is shown in the Fokker-Plank documentation. Cheers

**Comment by ChrisRackauckas** [comment]
The docs show how to do it yourself, but for this case you can note that boundary conditions essentially are just constraints, and you can use the integro-differential equation support to just define a constraint that the integral over the whole domain is equal to one. That is equivalent to then what is done "by hand" in the example.
